# Generated by Django 4.2.4 on 2023-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0003_remove_question_true_or_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='tests',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
